name: Jobs By City (EMAIL)

on:
#  schedule:
#    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Github Installation
        run: |
          sudo apt-get install -y git
      
      - name: Ritchie Installation & Initialization
        run: |
          curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
          echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin

      - name: Ritchie Formula Jobs (Python) Execution
        env:
            RIT_JOB_TITLE: "Java Developer"
            RIT_JOB_CITY: "Uberlandia"
            RIT_EMAIL_RECEIVER: ${{ secrets.RIT_EMAIL_RECEIVER }}
            RIT_SENDGRID_API_KEY: ${{ secrets.RIT_SENDGRID_API_KEY }}
            RIT_SENDGRID_EMAIL_SENDER: ${{ secrets.RIT_SENDGRID_EMAIL_SENDER }}  
        run: |
            cd $GITHUB_WORKSPACE/reports
            sudo rit add repo --provider="Github" --name="formulas-insights" --repoUrl="https://github.com/GuillaumeFalourd/formulas-insights" --priority=1
            sudo rit linkedin search jobs --rit_job_title= "$RIT_JOB_TITLE" --rit_job_city="RIT_JOB_CITY" --rit_send_email="yes" --rit_email_receiver="$RIT_EMAIL_RECEIVER"

      - name: Commit and Push new file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "add new report"
          git push